# Generated by Django 3.0.5 on 2024-12-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0007_auto_20241207_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_name',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_value',
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='test'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default='123', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
