# Generated by Django 3.0.5 on 2024-12-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0008_auto_20241207_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('Home', 'home'), ('Office', 'office'), ('Garage', 'garage')], default='apartment', max_length=50),
        ),
    ]
