# Generated by Django 3.0.5 on 2024-12-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0009_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='media.jpeg', upload_to='media/property_images'),
        ),
    ]
