# Generated by Django 3.0.5 on 2024-12-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0010_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='media.jpeg', upload_to='media/media/property_images'),
        ),
    ]
