# Generated by Django 3.0.5 on 2024-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0011_auto_20241209_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='media.jpeg', upload_to='media/property_images'),
        ),
    ]
