# Generated by Django 3.0.5 on 2024-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0012_auto_20241209_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='property_images/media.jpeg', upload_to='media/property_images'),
        ),
    ]
