# Generated by Django 3.0.5 on 2024-12-09 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0015_remove_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
