# Generated by Django 3.0.5 on 2024-12-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0016_propertyimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number_of_units',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='t_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('lease', 'Lease')], default='rent', max_length=50),
        ),
    ]
