# Generated by Django 3.0.5 on 2024-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0020_auto_20241211_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='landlord_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
