# Generated by Django 3.0.5 on 2024-12-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0021_auto_20241211_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='contact_number',
            field=models.CharField(blank=True, default='0711111', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('semi-furnished', 'Semi-Furnished'), ('unfurnished', 'Unfurnished')], default='unfurnished', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_features',
            field=models.TextField(blank=True, default='school', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('sold', 'Sold')], default='available', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities',
            field=models.TextField(blank=True, default='water', help_text='List included utilities (e.g., water, electricity).', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, default='gym', related_name='properties', to='property_app.Amenity'),
        ),
    ]
