# Generated by Django 3.0.5 on 2024-12-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0024_auto_20241213_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='pending', max_length=50),
        ),
    ]
