# Generated by Django 3.0.5 on 2024-12-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0025_auto_20241213_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
