# Generated by Django 3.0.5 on 2024-12-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0027_auto_20241213_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=200000.0, max_digits=10),
        ),
    ]
