# Generated by Django 3.0.5 on 2024-12-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0029_auto_20241214_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=6520000.0, max_digits=10),
        ),
    ]
