# Generated by Django 3.0.5 on 2024-12-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0031_auto_20241214_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=3000000.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
