# Generated by Django 3.0.5 on 2024-12-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0032_auto_20241214_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
