# Generated by Django 3.0.5 on 2024-12-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0038_auto_20241217_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property_app.Property'),
        ),
    ]
