# Generated by Django 3.0.5 on 2024-12-16 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import property_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0039_auto_20241217_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(default=property_app.models.get_default_user_john, on_delete=django.db.models.deletion.CASCADE, related_name='client_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='landlord',
            field=models.ForeignKey(default=property_app.models.get_default_landlord, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(default=property_app.models.get_default_property, on_delete=django.db.models.deletion.CASCADE, to='property_app.Property'),
        ),
    ]
