# Generated by Django 3.0.5 on 2024-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0041_auto_20241217_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='client_signature',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='landlord_signature',
        ),
        migrations.AddField(
            model_name='contract',
            name='client_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='landlord_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
