# Generated by Django 3.0.5 on 2024-12-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0043_auto_20241219_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='property_app.Property'),
        ),
    ]
