# Generated by Django 3.0.5 on 2024-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0044_auto_20241219_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
