# Generated by Django 5.1.3 on 2024-12-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0046_rename_property_contract_property_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=45785.0, max_digits=10),
        ),
    ]
