# Generated by Django 5.1.3 on 2024-12-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0047_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
