# Generated by Django 5.1.3 on 2024-12-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0048_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
