# Generated by Django 5.1.3 on 2024-12-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0049_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
    ]
