# Generated by Django 5.1.3 on 2024-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0050_remove_contract_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
