# Generated by Django 5.1.3 on 2024-12-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0051_remove_proposal_payment_status_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_qrcodes/'),
        ),
    ]
