# Generated by Django 5.1.3 on 2025-01-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0052_profile_qr_code_transaction_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='property_app.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='utilities',
            field=models.TextField(blank=True, help_text='List included utilities (e.g., water, electricity).', null=True),
        ),
    ]
